name: Go Checks

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Format
        run: go fmt ./...
        working-directory: app
      - name: Vet
        run: go vet ./...
        working-directory: app
      - name: Test
        run: go test ./...
        working-directory: app
