name: Go Build and Release

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for GoReleaser to compute changelogs

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.10'

      - name: Run tests
        run: go test ./...

      - name: Run GoReleaser (only on tag push)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}