# .github/workflows/release.yml
name: Build & Release (linux/amd64 + linux/arm64)

permissions:
  contents: write  # needed to create/update releases

on:
  push:
    tags:
      - 'v*'   # e.g. v1.2.3

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.10'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Build for linux/${{ matrix.arch }}
        env:
          GOOS: linux
          GOARCH: ${{ matrix.arch }}
        run: |
          # Your existing build: produces athletix.tar.gz
          make zip
          # Rename to include OS/arch so assets don't collide
          mv athletix.tar.gz "athletix-linux-${GOARCH}.tar.gz"

      - name: Upload to GitHub Release for this tag
        uses: softprops/action-gh-release@v2
        with:
          files: |
            athletix-linux-${{ matrix.arch }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
